spring.application.name=SpringPlayMySongs

# Configurações de upload de arquivos, para aceitar arquivos maiores
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
